### ISSUE TITLE
after update Hassio 2021.7.1

### ISSUE THREAD

**Issue by zlucio** [dylrio/hassio-ngrok#28]
After update 2021.7.1 .
Released: July 8, 2021y 8, 
NGROK doesn't work: 400: Bad Request returns.
 I tried to follow the instructions to configure HASSIO in the http section ..... but I don't know ip / subnet !!!!
Thank you

**Comment by Balbao** [comment]
I have the same problem. Since this update, ngrok does not work anymore.
400: Bad Request
Thank you for your solutions.

**Comment by zlucio** [comment]
> 
> 
> I have the same problem. Since this update, ngrok does not work anymore.
> 400: Bad Request
> Thank you for your solutions.


add in configuration.yaml

http:
    use_x_forwarded_for: true
    trusted_proxies:
    - 127.0.0.1
    - 172.30.32.0/24
    - 172.30.33.0/24

or check the subnet address and add !!!!

then restart and everything works

**Comment by Balbao** [comment]
> add in configuration.yaml
> 
> http:
> use_x_forwarded_for: true
> trusted_proxies:
> - 127.0.0.1
> - 172.30.32.0/24
> - 172.30.33.0/24
> 
> or check the subnet address and add !!!!
> 
> then restart and everything works


Yes, thank you very much. It works perfectly. :)

**Comment by zlucio** [comment]
👍

Il mar 13 lug 2021, 16:52 Balbao ***@***.***> ha scritto:

**Comment by bigmat73** [comment]
Hi,  i have same error with 2021.7 update.

I put this on config.yaml but, after checking, i have some error code... (
Component error: use_x_forwarded_for - Integration 'use_x_forwarded_for' not found.
Component error: trusted_proxies - Integration 'trusted_proxies' not found.) 

What is the good way to resolve this issue ?
I dont understand...

**Comment by bigmat73** [comment]
OK, i have plug my brain...
It is a indentation issue...

All is OK with fix http in config.yaml 🍾🎉

Thx so much !!

**Comment by zlucio** [comment]
👍

Il mer 14 lug 2021, 09:38 bigmat73 ***@***.***> ha scritto:

**Comment by dylrio** [comment]
Sorry for my absence on this project, I'm in the middle of a long-distance move and my HA isn't set up yet. 

Sounds like @zlucio's suggestion solved this so I will close it out. Thanks!

**Comment by Feedy88** [comment]
@zlucio sorry for replying to the closed issue. You mentioned to 
> or check the subnet address and add !!!!
Do you mean subdomain in this case? And where would I need to add this?

**Comment by dylrio** [comment]
@Feedy88 I think they're referring to the subnet for the proxy. I think Home Assistant Core needs the ip address of any reverse proxy now (which this essentially is). The ones they listed are the default ones assigned to add-ons, but if you have a non-standard setup you may need to find your own.

I'll plan on adding something to the docs for this, I've gotten a few questions on it since so I think that will help everyone.
